name: Auto Update Surge RULE-SET

# Trggier Rule
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:     # grant right to allow GitHub trigger manually

jobs:
  update-rules:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Download and Convert Rules
        run: |
          echo "Downloading hagezi pro++ wildcard domains..."
          # Download wildcard branch
          curl -sL "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus-onlydomains.txt" -o raw_pro_plus.txt
          curl -sL "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/multi-onlydomains.txt" -o raw_pro_normal.txt
          curl -sL "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif-onlydomains.txt" -o raw_tif.txt
          
          echo "Converting Surge DOMAIN-SET format..."
          awk '!/^#/ && NF {print "DOMAIN-SUFFIX," $1}' raw_pro_plus.txt > hagezi_pro_plus.list
          awk '!/^#/ && NF {print "DOMAIN-SUFFIX," $1}' raw_pro_normal.txt > hagezi_pro_normal.list
          awk '!/^#/ && NF {print "DOMAIN-SUFFIX," $1}' raw_tif.txt > hagezi_tif.list

          rm raw_pro_plus.txt raw_pro_normal.txt raw_tif.txt

      - name: Commit and Push Changes
        run: |
          # Setup Git Robot
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check updates, if yen then push
          if [ -n "$(git status --porcelain)" ]; then
            git add *.list
            git commit -m "Auto-update Surge rules: $(date +'%Y-%m-%d')"
            git pull --rebase
            git push
            echo "✅ Rules updated and Push!"
          else
            echo "🤷‍♂️ No need update Push."
          fi
